### ISSUE TITLE
Metric: policy evaluation counter

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#102]
The goal of this metric is to allow an operator to understand how many times a certain policy is evaluated.

The policy provides also some labels, that can be used to filter the metric and provide really specific data.

## Metric name

`kubewarden_policy_evaluations_total`

## Metric type

Counter

## Use cases

* How many requests have been evaluated inside of the cluster during a certain time frame
* How many requests have been blocked during the last hours
* How many requests have been accepted during the last hours
* How many requests have been mutated during the last hours
* How many Pod Creation requests have been blocked during the last hours

## Labels

* `policy_name`: name of the policy
* `resource_name`: name of the resource that has been evaluated by the policy
* `resouce_kind`: kind of the resource that has been evaluated by the policy. Eg: Pod, Deployment, Service,...
* `resource_namespace`: name of the Namespace the resource being evaluated belonged to. Of course that applies only to namespaced resources
* `resource_request_operation`: type of the operation (CREATE, UPDATE, DELETE)
* `accepted`: boolean value - final outcome of the evaluation
* `mutated`: boolean value - set to true when the request is accepted and mutated
* `error_code`: integer value - the error code that was returned by the policy. This only applies if the request was rejected, and is an optional field in all cases.

##  Deliverables

* [x] Instrument the policy-server code
* [x] Provide examples of PromQL queries that can take advantage of this metric

**Comment by ereslibre** [comment]
I think it should has one more label at least:

- `error_code`: the returned error code, if the request was rejected. Empty it not present.

Also, we might want to add `error_message` as well, but I'm not so sure about this one.

**Comment by flavio** [comment]
@ereslibre I think it would be used to have some rate metrics, for example (I haven't verified it):

Tracking the per-minute rate (averaged over 30s) at which requests are accepted:
```promql
rate(kubewarden_policy_evaluations_total{accepted="true"}[30s] == 1)*60
```
