### ISSUE TITLE
Document how to make Prometheus aware of the metrics exposed by Policy Server

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#106]
We need to provide some instructions about how to make Prometheus aware of the metrics exported by the Policy Server pods.

In the beginning we will assume Prometheus is running inside of the same cluster as Policy Server.

## Acceptance criteria

* Provide simple step-by-step instructions. The instructions will then become a document like [the one about tracing](https://docs.kubewarden.io/operator-manual/tracing/01-quickstart.html)

**Comment by jvanz** [comment]
As all related PR s are merged, I'm closing this issue.
