### ISSUE TITLE
Refactoring of the main function

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#13]
The `main` function is getting a bit crowded, also because of all the code that deals with the flags. We should probably split that up to a dedicated function and maybe even to a dedicated file.

**Comment by ereslibre** [comment]
It would be great to take this opportunity to check if it's feasible to move functionality and flags shared between the `policy-server` and the `policy-testdrive` to a common place.

**Comment by flavio** [comment]
I think we can close this issue, since we've done this refactoring sometimes ago
