### ISSUE TITLE
Allow mutating policies to behave as validating

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-server#137]
Add a new setting for every policy that specifies whether this policy is mutating or not. This field would be added to the [policy settings](https://github.com/kubewarden/policy-server/blob/adea2081933a9bc301131d28849a62c396ea1255/src/settings.rs#L11-L19).

The `ClusterAdmissionPolicy` already has a `mutating` field. The `kubewarden-controller` when writing the `policy-server` configuration has to add this `mutating` field as well (has to be added in https://github.com/kubewarden/policy-server/blob/adea2081933a9bc301131d28849a62c396ea1255/src/settings.rs#L11-L19).

The `policy-server` knows for every instantiated policy whether it's expected to behave as mutating or not. No changes are required nor in any policy or in the SDK's.

There are different cases:

1. Mutating policy with `mutating: false` in the Custom Resource. This means that despite the policy has the ability to accept a request by mutating it, we don't want to mutate (a `ValidatingWebhookConfiguration` will be created). In this case, the `policy-server` has to reject the request with a message describing that the policy would have accepted the request by mutating it, but it will be rejected as requested.
2. Mutating policy with `mutating: true`. Nothing changes. A `MutatingWebhookConfiguration` will be registered, and it's up to the policy code to either accept, mutate or reject the request.
3. Non-mutating policy with `mutating: false`. Nothing changes. A `ValidatingWebhookConfiguration` will be registered, and it's up to the policy code to either accept or reject the request.
4. Non-mutating policy with `mutating: true`. Nothing changes. We can write an INFO message on stderr describing that the policy will never mutate, just for the user to know that they are expecting mutating from a non-mutating policy. In terms of functionality, the policy works as expected, despite it only validates.

**Comment by jvanz** [comment]
I've proposed a fix for that. The related PR are:

- https://github.com/kubewarden/policy-server/pull/139
- https://github.com/kubewarden/policy-evaluator/pull/71
- https://github.com/kubewarden/kubewarden-controller/pull/141
- https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/5

**Comment by chrisns** [comment]
👋 happy new year etc :) any idea on when this can be merged in? 😄

**Comment by jvanz** [comment]
> wave happy new year etc :) any idea on when this can be merged in? smile

Hi @chrisns ! Happy new year! I hope you've enjoyed good food and time with nice people during these days!

Back to business... I'm working on this. I came back from vacation yesterday and this is one of my top priorities. ;)
