### ISSUE TITLE
Add testing and CI

### ISSUE THREAD

**Issue by cmurphy** [kubewarden/policy-server#14]
There are not yet any tests or automated PR verification. We should add:

- [x] Automated linting/formatting
- [x] Unit tests
- [x] Functional and/or end-to-end tests
- [x] Performance benchmark tests: https://github.com/kubewarden/load-testing
- [x] Github Actions workflows to perform these tests for every pull request

**Comment by flavio** [comment]
I've updated the card to reflect the progress we've made on this topic since the card was created.

**Comment by flavio** [comment]
We forgot to close this card, everything has been implemented
