### ISSUE TITLE
Feature Request: support Kubernetes' `warning` admission control response

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-server#189]
### Is your feature request related to a problem?

No

### Solution you'd like

I think we should consider supporting `warnings`, as supported by [Kubernetes v1.19 onwards](https://kubernetes.io/blog/2020/09/03/warnings/).

A response looks like this:

```json
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "response": {
    "uid": "<value from request.uid>",
    "allowed": true,
    "warnings": [
      "duplicate envvar entries specified with name MY_ENV",
      "memory request less than 4MB specified for container mycontainer, which will not start successfully"
    ]
  }
}
```

Policies should be able to emit warning messages if desired. The API consumer at the other end (e.g. using `kubectl`) will see the warning printed in their `stderr` stream. Every client is free to do whatever they want with this information (printing it as is to `stderr` is just what `kubectl` does).

For implementing this feature, we would have to extend the languages SDK's, and the guest/host interface of waPC.

Adding the question label to raise this discussion: do we want to support this? My initial opinion is yes.

Adding the epic label because this implies a number of components and this issue could work as an umbrella issue.

**Comment by viccuad** [comment]
This looks like a super useful thing! But I haven't looked much about into the `warnings` I have to say.

Would this be a precondition for https://github.com/kubewarden/kubewarden-controller/blob/main/rfc/0002-audit-mode.md?

**Comment by ereslibre** [comment]
> Would this be a precondition for https://github.com/kubewarden/kubewarden-controller/blob/main/rfc/0002-audit-mode.md?

No, it's orthogonal.

**Comment by flavio** [comment]
I like this idea too. We can work on that in the future, right now I don't think it has a high priority
