### ISSUE TITLE
[Epic] Add metrics endpoint

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-server#19]
Adding metrics can help to improve observability.

For example:
* Number of policies are loaded into the policy server
* Mean response time of the policies, generally speaking but also at a policy level (eg: the privileged-pods policy has a mean response time of XXX)
* Number of failures (globally, per policy)
* Number of rejections (globally, per policy)
* many more...

# Why this is needed

Users can leverage tools like Prometheus to scrape these metrics and then:
* Plot statistics about the policy server (eg: memory/cpu used)
* Set alerts when something bad happens (eg: no instances running, all instances slowed down)

This can also help users to better define the deployment details of the server (number of replicas, resource limits,...)

# Related issues

This is just an epic, the work of implementing that is done inside of these epics:

* [x] https://github.com/kubewarden/policy-server/issues/102
* [x] https://github.com/kubewarden/policy-server/issues/103

**Comment by jvanz** [comment]
All the tasks are done. Closing this one.
