### ISSUE TITLE
Allow policies to pull information from the Kubernetes cluster

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-server#21]
Allow guest policies to pull information from the Kubernetes cluster. This information can be a list of well-known type of resources and could be cached by the policy server, served from the cache to the guest policy. This allows a guest policy to take more complex decisions, based on the current status of the cluster.

For example, if a resource is namespaced, we can add a way to retrieve the namespace it belongs to, so the policy can read the annotations and labels.

In general, we could allow the policy to read arbitrary information (a fixed list of well known resources).

**Comment by flavio** [comment]
Also, this would allow to have policies like the following one from OPA: https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/

**Comment by flavio** [comment]
This is done as part of Kubewarden 1.6.0
