### ISSUE TITLE
Feature Request:  Allow DNS Lookups from kubewarden Modules

### ISSUE THREAD

**Issue by floriankoch** [kubewarden/policy-server#236]
### Is your feature request related to a problem?

I try to validate if all Hosts inside a Ingress have a corresponding DNS Entry

### Solution you'd like

I like to use e.g. the Golang Function net.LookupIP to resolve the Domains

**Comment by flavio** [comment]
This is the list of changes that have to be done:

* [ ] extend policy evaluator: https://github.com/kubewarden/policy-evaluator/pull/119
* [ ] extend rust SDK: https://github.com/kubewarden/policy-sdk-rust/pull/36
* [ ] extend kwcl: https://github.com/kubewarden/kwctl/pull/212
* [ ] extend policy-server
* [ ] extend go SDK
* [ ] extend Swift SDK

**Comment by floriankoch** [comment]
@flavio   great news thank you
