### ISSUE TITLE
[Not confirmed] Pulling from Azure Container Registry in authenticated mode is failing

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-server#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever `kwctl` or `policy-server` tries to pull a policy from the Azure Container Registry, the user is receiving an error `[{"code":"UNAUTHORIZED","message":"Invalid clientid or client secret."}]}`.

This issue is to recreate this environment and confirm the bug if we can reproduce.

All configuration seems fine, and the user reports that they can pull with this very same configuration by using `docker`, but fails with this error when using `kwctl pull`:

```
$ kwctl-linux-x86_64 pull registry://xxx.azurecr.io/policies/namespace_prefix_validator:v0.1.0
Error: the policy registry://xxx.azurecr.io/policies/namespace_prefix_validator:v0.1.0 could not be downloaded due to error: Authentication failure: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}
```

### Expected Behavior

`kwctl` or the policy server pulls the policy.

### Environment

```markdown
- OS: Linux
- Architecture: amd64
```

**Comment by floriankoch** [comment]
@ereslibre  thx

**Comment by ereslibre** [comment]
The user reports that the admin user is disabled in the Azure Container Registry.

**Comment by floriankoch** [comment]
@ereslibre it seems to work with an ACR with admin user access

**Comment by ereslibre** [comment]
> @ereslibre it seems to work with an ACR with admin user access

Thank you @floriankoch. This is a great pointer.

**Comment by flavio** [comment]
@floriankoch This seems kinda a duplicate of https://github.com/kubewarden/kwctl/issues/210

I tried to reproduce it sometimes ago, but without luck (see https://github.com/kubewarden/kwctl/issues/210#issuecomment-1115881065)

Can you share more details about how the docker config file is being created? (something similar to the steps I described in the linked issue)

**Comment by floriankoch** [comment]
@flavio yes i think its the same problem

Which Access mode have you tested?
Azure ACR has 2 modes 

1. Admin Access
This is basically the same as  login with username & password

3. Azure AD Integrated Access 
You need to authenticate against Azure AD, in the docker case you get an jwt, and this seems not to work

**Comment by flavio** [comment]
> @flavio yes i think its the same problem
>     1. Admin Access
>        This is basically the same as  login with username & password

I think this is what I have done because in the end I got a username and password. Can you look at the linked comment to confirm? I'm new to ACR

>     2. Azure AD Integrated Access
>        You need to authenticate against Azure AD, in the docker case you get an jwt, and this seems not to work

This is probably not going to work because I suspect the oci-distribution library supports only username & password out of the box... that would need some double checking.

**Comment by floriankoch** [comment]
@flavio no, you testet the non Admin user (wich ist the better way) , you created a Service Principal , and RBAC Permissions 

@ereslibre @flavio   it works with kwctl now - not with the policy server -

**Comment by floriankoch** [comment]
@flavio @ereslibre   got it working 

my fault was using this command (from the kubernetes docs https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
`kubectl create secret generic--from-file=.dockerconfigjson=/home/codespace/.docker/config.json     --type=kubernetes.io/dockerconfigjson `

here the decoded base64 looks exactly like the config.json

If i use this , it works 
` kubectl create secret docker-registry dockercfg --from-file=.dockerconfigjson=/home/codespace/.docker/config.json  
`
here the decoded base64 looks corret , with userename and password

**Comment by flavio** [comment]
This is pretty odd, here both commands lead to the creation of the same Secret object. The value `.dockerconfigjson` is identical in both cases :thinking: 

Anyhow, I'm glad this is working fine now. Can we close this issue?

**Comment by floriankoch** [comment]
@flavio   for me, we can close this - but the generated secret objects are different in my case

**Comment by ereslibre** [comment]
I also ran both commands creating two different secrets and their relevant content matches here as well. Since this seems an issue with the secret generation I think we can close this issue.
