### ISSUE TITLE
Add some way to version our policy wasm files

### ISSUE THREAD

**Issue by kkaempf** [kubewarden/policy-server#29]
The policy format already changed once (when we from WASI to waPC). There are chances this will happen again in the future (see the #28 ).

When the policy format changes, we have to find a way to not load policies written with the old format into policy-server.

# Acceptance criteria

* It's possible to query the spec version of a Kubewarden policy
* Extra: the policy-server refuses to load older policies and exits with an error at boot time

**Comment by flavio** [comment]
@kkaempf we recently discussed that during one of our dailies. I think we both agree the `later` tag should be removed and this issue should be done before the initial release.

Am I right?

**Comment by ereslibre** [comment]
IIRC what we discussed is that we can introduce the versioning part after MVP, and re push wasm artifacts at some point with this metadata, given that there are very low chances that anybody is depending on this artifacts, cached somehow at this time.

**Comment by flavio** [comment]
This is done now
