### ISSUE TITLE
Release workflow  is flacky due connection issues with `musl` 

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From time to time, building the ARM release of Policy Server fails. The failure happens because there's an error downloading the musl release we use to perform the cross build.

This is really bad, because it doesn't allow us to release new features/fixes.

### Expected Behavior

First of all, the build should be stable. It should be green every time.

While addressing this issue, it would be nice (but not mandatory) to address also these current limitations:

  * We are downloading a musl release that is not versioned. This makes things not reproducible and less predictable.
  * When doing a SBOM, this would be problematic

Currently we are using a two stage build process. The 1st stage builds a statically linked binary for policy-server, which is then copied into a distroless container.

Maybe we can perform stage 1 inside some linux distribution container image which comes with the musl toolkit.

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by jvanz** [comment]
It is not just ARM which has flacky build. There are x86_64 builds failing as well. All the build failed due `connection time out`.  I worked in the our actions to remove the need to download the `musl` libc every build and so on. In this new approach it still necessary to download the tarball at least once a month. Just to ensure that we will not forget to update something... However during my  workflow testing of this monthly job, the build still fails due connection time out. But I can download the file locally... :shrug:

I think there is something wrong with Github actions.

**Comment by jvanz** [comment]
This is same problem reported at https://github.com/kubewarden/kwctl/issues/281

**Comment by jvanz** [comment]
My fears have been confirmed: https://github.com/orgs/community/discussions/27906
