### ISSUE TITLE
Single failure in downloading policy causes policy-server to go to crashloop

### ISSUE THREAD

**Issue by Martin-Weiss** [kubewarden/policy-server#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In case a policy is configured that leads to a failure in downloading - the whole policy-server fails to load and is not available due to that.

### Expected Behavior

The policy server should be up and running for all "other" policies even in case it fails to download one of them.
A single failed download should not cause the whole policy server to fail.

### Steps To Reproduce

Deploy kubewarden
Configure the kubewarden-default helm chart to have one policy not being available.

### Environment

```markdown
- OS: Linux
- Architecture: x86_64
```

**Comment by Martin-Weiss** [comment]
```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  22s               default-scheduler  Successfully assigned kubewarden/policy-server-default-68b5f477b7-vxjh9 to rancher-master-03
  Normal   Pulled     4s (x3 over 22s)  kubelet            Container image "ghcr.io/kubewarden/policy-server:v1.3.0" already present on machine
  Normal   Created    4s (x3 over 22s)  kubelet            Created container policy-server-default
  Normal   Started    3s (x3 over 21s)  kubelet            Started container policy-server-default
  Warning  Unhealthy  2s (x7 over 21s)  kubelet            Readiness probe failed: Get "https://172.27.2.194:8443/readiness": dial tcp 172.27.2.194:8443: connect: connection refused
  Warning  BackOff    1s (x2 over 15s)  kubelet            Back-off restarting failed container

```

```
2022-11-23T08:05:31.103972Z  INFO policy_server::policy_downloader: policies download download_dir="/tmp" policies_count=6 status="init"
2022-11-23T08:05:31.104074Z ERROR policy_server: error while downloading policy clusterwide-no-privileged-pod from registry01.suse:5000/rke-prod/ghcr.io/kubewarden/policies/pod-privileged:v0.2.1: unknown scheme: registry01.suse
```

**Comment by viccuad** [comment]
Hi, thanks for opening this issue!

In this case, everything is working as expected, there's no degraded service.

The policy-server Deployment does Rollouts; if you had previous Pods of policy-server working and ready, they will keep processing the policy calls, until a new working Pod is ready, and the webhooks are pointed to the new ready Pod. Only then the old Pods will be deleted, and once the deletion is successful, the webhooks are pointed to the new ready Pod.

In the case of the first policy-server Deployment (and therefore Pod), so probably this case in this issue, everything is also fine, as policies won't be active until the policy server is ready. Therefore no webhooks will be created until all policies all downloaded, configured and in `active` state. Which means Kubernetes resources can be created without any problem.

We are consciously reporting errors early for now. Users normally don't continually create and update ClusterAdmissionPolicies/AdmissionPolicies, hence we go with knowing that a policy is not working as soon as possible, yet not degrading usage of neither Kubewarden nor the cluster.

Closing as resolved.
