### ISSUE TITLE
Revisit context-aware deployment on Kubernetes

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-server#42]
Right now, all tests with context-aware features have been done manually or reusing a local kubeconfig (that is usually an admin kubeconfig locally). In the real deployment, we have to take care of RBAC permissions, so when a user deploys the policy-server, it has permissions to list the current hardcoded resources it is listing right now:

- Namespaces
- Services
- Ingresses

Of course, when we generalize this API types (and also allow CRD's to be listed and watched), we will have to easily allow the user grant permissions when deploying/redeploying the policy-server with the helm chart.

**Comment by flavio** [comment]
We will need to update the `all.yaml` file inside of this repository, plus the RBAC policy created by our [helm chart](https://github.com/chimera-kube/helm-charts)

**Comment by ereslibre** [comment]
This information is exposed in the helm chart now.
