### ISSUE TITLE
chore(deps): update to latest version of opentelemetry

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#493]
Update to latest version of the opentelemetry crate.

This is going to fix https://github.com/kubewarden/policy-server/pull/465 and https://github.com/kubewarden/policy-server/pull/439

**Comment by flavio** [comment]
Moving to blocked. I looked into the upgrade and I discovered the current `main` branch of opentelemetry has already a different API.

I propose to look back into this issue as soon as the next version of the opentelemetry crates are released.

Apparently there's already an [issue](https://github.com/open-telemetry/opentelemetry-rust/issues/1100) open about tagging a new releases that includes these changes

**Comment by fabriziosestito** [comment]
update the controller dependency: See https://github.com/kubewarden/kubewarden-controller/pull/458
