### ISSUE TITLE
policy-testdrive: remove confusing panic message

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#50]
Since the introduction of context-aware policies, the policy-testdrive can produce confusing message when there's no connection available to the k8s cluster defined inside of `~/.kube/config`.

For example, this is the output produced on my machine when my `minikube` server is down:

```shell
policy-testdrive --policy module.wasm --request-file pod-req-no-specific-apparmor-profile.json 
thread '<unnamed>' panicked at 'could not initialize Kubernetes client: Error loading kubeconfig: Failed to infer config.. cluster env: (Error loading kubeconfig: Unable to load in cluster config, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined), kubeconfig: (Error loading kubeconfig: Unable to load current context: )', crates/policy-evaluator/src/cluster_context.rs:74:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Settings validation result: SettingsValidationResponse { valid: true, message: None }
Policy evaluation results:
ValidationResponse { uid: "", allowed: true, patch_type: None, patch: None, status: None }
```

# Acceptance criteria

No panic message is printed, instead a nicer warning message should be shown. Something that tells:
  1. cannot reach the Kubernetes cluster defined inside of your configuration
  1. context-aware policies are not going to be working

**Comment by ereslibre** [comment]
To add more information to this while reproducing. There are different behaviors that can happen with invalid configurations.

- A syntactically valid `kubeconfig` file, with unreachable Kubernetes cluster does not panic but does not inform the user that contextual policies might not work as expected.

- A syntactically invalid `kubeconfig` file does not panic, but does not inform the user.

- A completely missing `kubeconfig` file makes the `testdrive` panic.

Handle all these cases so we inform the user about the situation WRT to contextual policies as the acceptance criteria describes.,
