### ISSUE TITLE
Provide /healthz endpoint

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#7]
Provide a endpoint that could be used by Kubernetes to figure out if the application is healthy.

# Why this is needed

Kubernetes can monitor the health status of the policy-server instances by querying this `/healthz` endpoint. When a policy-server instance is unhealthy it (Kubernetes) will take care of starting a new Pod and killing the unhealthy one.

**Comment by nitishm** [comment]
@flavio I can take this up. How do determine the health of the policy-server? What checks should we perform?

**Comment by flavio** [comment]
Sorry for the long delay caused by the holidays.

This is an issue we created a long time ago, thinking about how things evolved I struggle to decide what we should use to understand if Policy Server is healthy.

PolicyServer will abort the bootstrap phase is any of its policy is cannot be loaded properly or if there's some incompatibility between the server and the policy.

Maybe we could monitor the health status of the different PolicyEveluator that are used to answer the requests... But how to monitor that is not clear to me. The only thing that comes to my mind is to ensure all the PolicyEvaluator(s) are still listening on their end of the tokio channels. When a PolicyEvaluator faces an internal error (like a `panic`) the channel would get closed.

However this is something we have never seen, we have been careful in handling all the errors and the code should not panic.

Unless @ereslibre has better ideas, I would temporarily close this issue until we have better ideas about what to monitor.

**Comment by ereslibre** [comment]
> The only thing that comes to my mind is to ensure all the PolicyEvaluator(s) are still listening on their end of the tokio channels. When a PolicyEvaluator faces an internal error (like a panic) the channel would get closed.

+1

Despite I have some ideas I wonder what would involve meaningful health checks. I think we need more experimental experience to know what health checks would be appropriate.

I agree in closing this issue for now and learn with experience. I will just drop some off the top of my head ideas:

- Is the HTTP server responding?
- For every loaded policy.
  - Is it able to process a new request?
  - Is the PolicyEvaluator able to perform a remote procedure call on the policy? A note: how does an infinite loop in a policy impact the policy evaluator?

**Comment by flavio** [comment]
Temporarily closing
