### ISSUE TITLE
Error: No such file or directory (os error 2) when starting PolicyServer

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/policy-server#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After merging sigstore related fixes, we have Error: No such file or directory (os error 2).
This is caused by the sigstore cache directory not being found, see https://github.com/kubewarden/policy-server/blob/30c2cdb7efec01201342aa41579296b8bccbad29/src/lib.rs#L66

### Steps To Reproduce

Start the latest policy server

**Comment by kravciak** [comment]
Fleet is passing again, thanks for the fix.
https://github.com/rancher/kubewarden-ui/actions/runs/8715088469/job/23916630355.
