### ISSUE TITLE
Metrics not generated

### ISSUE THREAD

**Issue by jvanz** [kubewarden/policy-server#847]
During the testing of the Kubewarden `v1.15.0` release candidates we noticed that policy server is not generating metrics. When the metrics are fetched from the OpenTelemetry collector endpoint the returned file is empty. We need to investigate if this is related to the recent libraries [updates](https://github.com/kubewarden/policy-server/pull/835) or is something else. 

The metrics can be fetched using a command like this:
```
kubectl run curlpod -t -i --rm --wait --image curlimages/curl:8.00.1 --restart=Never -- --silent policy-server-default.kubewarden.svc.cluster.local:8080/metrics
```

#### Acceptance criteria
- Investigate why the metrics are not being generated
- Fix policy server metrics to generate and exposed in the OpTel collector endpoint

**Comment by viccuad** [comment]
Adding info:
policy-server-1.15.0-rc2 metrics don't work by following the steps in docs.kubewarden.io. Neither with the deps versions of docs.kubewarden.io (`opentelemetry-operator-0.56.0` , `jaeger-operator-2.49.0` , `kube-prometheus-stack-51.5.3`), nor with latest at the time of writing `opentelemetry-operator-0.64.4`, `jaeger-operator-2.54.0`, `kube-prometheus-stack-61.3.2`.

policy-server-1.14.0 works with the steps and versions of docs.kubewarden.io.

**Comment by viccuad** [comment]
Another data point.
Having a completely working Kubewarden 1.14 with the deps from docs, I started upgrading to 1.15.0-rc2. Using chart `kubewarden-controller-1.15.0-rc2` with `kubewarden-defaults-v1.14.0` works. Upgrading to `kubewarden-defaults-v1.15.0-rc2` breaks metrics.
Which corroborates the theory that policy-server metrics are broken in rc2 and the controller is fine.

**Comment by jvanz** [comment]
@fabriziosestito @viccuad thanks for the fix! Furthermore, sorry for missing this issue when I've updated the libraries. I've testing the tracing only and did not read properly the changelog.
