### ISSUE TITLE
Report loaded and updated policies in the log

### ISSUE THREAD

**Issue by kkaempf** [kubewarden/policy-server#88]
When I update the `pod-privileged` policy (because of kubewarden/kubewarden.io#26), `helm` just reports
> clusteradmissionpolicy.policies.kubewarden.io/privileged-pods configured

So I looked at the `policy-server` logs (using [k9s](https://k9scli.io)) to get some more information but it only shows

> Sep 17 08:56:33.432  INFO policy_server: policies download download_dir="/tmp/" policies_count=1 status="init"                                                                             
> pulling policy...
> Sep 17 08:56:35.216  INFO policy_server: policies download status="done" 
> Sep 17 08:56:35.216  INFO policy_server: kubernetes poller bootstrap status="init"
> Sep 17 08:56:35.216  INFO policy_server: kubernetes poller bootstrap status="done" 
> Sep 17 08:56:35.216  INFO policy_server: worker pool bootstrap status="init"
> Sep 17 08:56:35.216  INFO policy_server::kube_poller: spawning cluster context refresh loop                                                                                             
> Sep 17 08:56:35.229  INFO policy_server::worker_pool: spawning worker spawned=2 total=2
> Sep 17 08:56:35.230  INFO policy_server::worker_pool: spawning worker spawned=1 total=2                                                                                                    
> Sep 17 08:56:35.328  INFO policy_server: worker pool bootstrap status="done"                                                                                                               
> Sep 17 08:56:35.333  INFO policy_server::server: started HTTPS server address="0.0.0.0:8443"  

which doesn't tell me anything about

- which policy was pulled
- which version of this policy
- was it running before (is it an update) or not (is it a new policy)
- which other policies are running (in which version)

While the current log is helpful for developers, it doesn't contain information relevant for operators.

**Comment by ereslibre** [comment]
Related PR's:

- https://github.com/kubewarden/policy-fetcher/pull/24
- https://github.com/kubewarden/policy-server/pull/119
- https://github.com/kubewarden/kwctl/pull/83
