### ISSUE TITLE
Support send data to remote Otel collector

### ISSUE THREAD

**Issue by jvanz** [kubewarden/policy-server#993]
This issue is keep track of a subset of the changes necessary to allow Kubewarden send data to remote OpenTelemetry (Otel) collectors. As described in https://github.com/kubewarden/kubewarden-controller/issues/931.

Currently, the policy server is able to send data to a Otel collector running as sidecar. It's necessary to change exporter in the code to send data to a remote Otel collector.

### Acceptance criteria
- [x] Change the metrics/tracing exporter to consider the environment variables to configure the Otel exporter.
- [ ] Add configuration to store the location of the certificate to be used in the secure communication with Otel collector
  - Consider contributing upstream in the OpenTelemetry rust library to load the certificate path also from environment variable. As it's done in the Go lang libraries

**Comment by fabriziosestito** [comment]
The configuration will initially be implemented in the policy server using CLI flags or environment variables. Once completed, contributions will be made upstream, as the upstream merge process might take some time.
